### PR TITLE
Toby cbe amend

### PR DESCRIPTION
**Pull request by tobycheung0000**
1) Adding decscription of air speed fixed at 0.2m/s for PMV calculation in ankle draft risk model. 
2) Adding warning sign if MET > 1.3 or Clo > 0.7
3) Description in "Help" is also added.

### CODE REVIEW

**Comment by thoyt** [comment]
Hi @tobycheung0000  - It looks like you reverted the first commit, so there aren't any changes to review. Are you missing a commit somewhere?

**Comment by tobycheung0000** [comment]
Hi Tyler,

For me, I can see both commits on 10 July and 26 July on Githuh with all
changes inside. As show below:


and





The following is the Github apps screenshot that I am using in my computer:


Can you let me know what I should do so that you can see the changes?  Thank
you!


Best,
Toby

Toby C.T. Cheung, Ph.D.

Research Fellow,  Berkeley Education Alliance for Research in Singapore

1 Create Way, #11-01 Create Tower, Singapore 138602
Phone: (SG) +65-9456-4711 <%2B65-8283-5756> (HK) +852-6019-4020
<%2B1-352-871-4100>

**Comment by tobycheung0000** [comment]
Hi Tyler,

Now I know what is the problem. My apology on the mistake.
Is that okay for you just approve the first commits   5c010cf
<https://github.com/CenterForTheBuiltEnvironment/comfort_tool/commit/5c010cf3cf6e74d6cca5f2aae2ff9804500484bb>
with
changes compared to the master branch?
If not, I will need to commit another pull request, isn't  it?

Best,
Toby

Toby C.T. Cheung, Ph.D.

Research Fellow,  Berkeley Education Alliance for Research in Singapore

1 Create Way, #11-01 Create Tower, Singapore 138602
Phone: (SG) +65-9456-4711 <%2B65-8283-5756> (HK) +852-6019-4020
<%2B1-352-871-4100>

**Comment by thoyt** [comment]
@tobycheung0000 You can revert the revert commit with `git revert 2e5d16e` then push your branch. If you need to make another pull request that's fine.

**Pull request merged**
